### ISSUE TITLE
Something wrong in the 3d reconstruction

### ISSUE THREAD

**Issue by rustyjerry** [TemugeB/CDRnet#3]
I downloaded the trained model that you provided. It works fine with the 2d prediction but the 3d predicted graph only shows a line or even a red dot. 
![Figure_1](https://user-images.githubusercontent.com/60071977/175374827-1e53d8ac-8857-4da0-aa45-a68a4968c9c9.png)
![Figure_2](https://user-images.githubusercontent.com/60071977/175374848-405c7cd3-6237-47d7-8e70-628e0c65989f.png)

**Comment by TemugeB** [comment]
Hmm this is a weird one. I will take a look. You didn't change anything with the test code? If not, might be an issue with using ```tf.linalg.solve```. Which version of Tensorflow are you using? 

By the way, are you planning to use this package for real world application? I would advise against it, since it is trained on a specific dataset only. If you need a real-time 3D pose estimator, go to my other repository here: [bodypose3d](https://github.com/TemugeB/bodypose3d). It works relatively well on real world application.

**Comment by TemugeB** [comment]
I'm not sure what the problem is. I've re-downloaded everything and tried running the code. It seems to be working fine on my end, which is a completely different machine from the one I used to train the model. 
![image](https://user-images.githubusercontent.com/36071915/175461943-ea322e3e-d078-4747-96bc-bb16b8aec84a.png)

**Comment by TemugeB** [comment]
Closing issue due to being stale.
